CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `dob` date DEFAULT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `role` enum('customer', 'admin') DEFAULT 'customer',
  `check_status` enum('true',  'false') DEFAULT 'true',
  `status` enum('A', 'IA') DEFAULT 'A',
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_date` datetime DEFAULT (CURRENT_DATE),
  `updated_by` VARCHAR(100) DEFAULT NULL,
  `updated_date` datetime DEFAULT (CURRENT_DATE)
);


insert into users (first_name, last_name, email, password, dob, phone_number, role) values ('Admin', '', 'balajievil13@gmail.com', 'Admin@123', '2000-02-13T0', '9789324961','admin' )

 alter table users add column `created_by` VARCHAR(100) not NULL;


 -- select * from aerp_master_item limit 1 \G;
-- CREATE TABLE db1.table1 SELECT * FROM db2.table1

 CREATE TABLE `item_move_status` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `mov_status` VARCHAR(75) NOT NULL,
  `min_time` VARCHAR(50) NOT NULL,
  `max_time` VARCHAR(50) NOT NULL,
  `status` enum('A', 'IA') DEFAULT 'A',
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_date` datetime DEFAULT (CURRENT_DATE),
  `updated_by` VARCHAR(100) DEFAULT NULL,
  `updated_date` datetime DEFAULT (CURRENT_DATE)
);


insert into item_move_status (mov_status, min_time, max_time) values ('Fast Moving', '1', '7'), ('Medium Moving', '2', '10'), ('Slow Moving', '2', '15');


CREATE TABLE `storage_mstr` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `strg_name` VARCHAR(75) NOT NULL,
  `min_capacity` VARCHAR(50) NOT NULL,
  `max_capacity` VARCHAR(50) NOT NULL,
  `location` VARCHAR(150) NOT NULL,
  `status` enum('A', 'IA') DEFAULT 'A',
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_date` datetime DEFAULT (CURRENT_DATE),
  `updated_by` VARCHAR(100) DEFAULT NULL,
  `updated_date` datetime DEFAULT (CURRENT_DATE)
);

    -- Sample Table for main product

CREATE TABLE `aerp_master_item` (
  `MI_KEY` int NOT NULL,
  `U_ITEM_CODE` varchar(30) DEFAULT NULL,
  `ITEM_CODE` varchar(6) DEFAULT NULL,
  `THICKNESS_DIA` varchar(3) DEFAULT NULL,
  `COLOR_CODE` varchar(2) DEFAULT NULL,
  `MANU_CODE` varchar(3) DEFAULT NULL,
  `MATERIAL_TYPE_CODE` varchar(3) DEFAULT NULL,
  `item_key` int DEFAULT '0',
  `thickness_dia_key` int DEFAULT '0',
  `color_key` int DEFAULT '0',
  `manu_key` int DEFAULT '0',
  `material_type_key` int DEFAULT '0',
  `REMARKS` varchar(150) DEFAULT NULL,
  `SHORT_DESC` varchar(100) DEFAULT NULL,
  `LONG_DESC` varchar(100) DEFAULT NULL,
  `tally_item_desc` varchar(100) DEFAULT NULL,
  `TYPE` int DEFAULT NULL,
  `MIN_INVENTARY` double(18,2) DEFAULT '0.00',
  `MIN_REODR_QTY` double(18,2) DEFAULT '0.00',
  `MAX_REODR_QTY` double(18,2) DEFAULT '0.00',
  `MAX_INVENTAR` double(18,2) DEFAULT '0.00',
  `LIST_PRICE` double(18,2) DEFAULT NULL,
  `standard_price` double(18,2) DEFAULT NULL,
  `mrp_rate` double(18,2) DEFAULT '0.00',
  `basic_pur_cost` double(18,2) DEFAULT '0.00',
  `stock_trnf_price` double(18,2) DEFAULT '0.00',
  `item_moving_status` varchar(5) DEFAULT NULL,
  `BOM` int DEFAULT '0',
  `CATALOG_NO` varchar(60) DEFAULT NULL,
  `MIN_REODR_LEVEL` double(18,2) DEFAULT NULL,
  `MAX_STOCK_LEVEL` double(18,2) DEFAULT NULL,
  `MIN_SALES_QTY` double(18,2) DEFAULT '0.00',
  `item_type` varchar(5) DEFAULT NULL,
  `item_type_key` int DEFAULT NULL,
  `category7_key` int DEFAULT NULL,
  `grade_desc` varchar(25) DEFAULT NULL,
  `SHORT_NAME` varchar(20) DEFAULT NULL,
  `DISORDER` int DEFAULT NULL,
  `display_code` varchar(75) DEFAULT NULL,
  `ACTIVE_STATUS` int DEFAULT NULL,
  `tariff_sh_no` varchar(15) DEFAULT NULL,
  `lp_tax_key` int DEFAULT NULL,
  `op_tax_key` int DEFAULT NULL,
  `discount_per` double(5,2) DEFAULT '0.00',
  `item_base_unit` varchar(5) DEFAULT '',
  `item_package_unit` varchar(5) DEFAULT '',
  `item_pack_to_base_conversion` decimal(5,2) DEFAULT '1.00',
  `mail_status` varchar(1) DEFAULT 'N',
  `created_by` int DEFAULT '0',
  `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by` int DEFAULT '0',
  `modified_on` datetime DEFAULT CURRENT_TIMESTAMP,
  `mi_post_status` int DEFAULT '0' COMMENT '0-Not Posted 1-Posted',
  `igst_percent` double(18,2) DEFAULT '0.00',
  `sgst_percent` double(18,2) DEFAULT '0.00',
  `cgst_percent` double(18,2) DEFAULT '0.00',
  `ugst_percent` double(18,2) DEFAULT '0.00',
  `lead_time` int DEFAULT NULL,
  `total_weight` double(18,2) DEFAULT '0.00',
  `commision_apply` varchar(5) DEFAULT '',
  `weight_unit` varchar(11) DEFAULT NULL,
  `prd_type` varchar(11) DEFAULT NULL,
  `comm_percent` double(6,2) DEFAULT '0.00',
  `ecomm_display_order` int DEFAULT '0',
  `new_product` int DEFAULT '0',
  PRIMARY KEY (`MI_KEY`),
  KEY `AERP_MASTER_ITEM_INDEX` (`MI_KEY`,`U_ITEM_CODE`(10)),
  KEY `CATALOG_NO` (`CATALOG_NO`),
  KEY `CATALOG_NO_2` (`CATALOG_NO`),
  KEY `CATALOG_NO_3` (`CATALOG_NO`),
  KEY `item_key` (`item_key`),
  KEY `manu_key` (`manu_key`),
  KEY `MI_KEY` (`MI_KEY`),
  KEY `display_code` (`display_code`),
  KEY `ACTIVE_STATUS` (`ACTIVE_STATUS`),
  KEY `display_code_2` (`display_code`),
  KEY `ACTIVE_STATUS_2` (`ACTIVE_STATUS`),
  KEY `CATALOG_NO_4` (`CATALOG_NO`) USING BTREE,
  KEY `REMARKS` (`REMARKS`) USING BTREE,
  KEY `master_item_status` (`ACTIVE_STATUS`),
  KEY `item_moving_status` (`item_moving_status`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 |



 CREATE TABLE `product_mstr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cat1_key` int DEFAULT '0',
  `cat2_key` int DEFAULT '0',
  `cat3_key` int DEFAULT '0',
  `cat4_key` int DEFAULT '0',
  `cat5_key` int DEFAULT '0',
  `cat6_key` int DEFAULT '0',
  `cat7_key` int DEFAULT '0',
  `part_no` VARCHAR(100) DEFAULT NULL,
  `prod_name` VARCHAR(100) NOT NULL,
  `short_name` VARCHAR(100) NOT NULL,
  `remark` VARCHAR(255) NULL,
  `HSN_code` VARCHAR(75) NULL,
  `mrp_price` VARCHAR(75) NULL,
  `sales_price` VARCHAR(75) NULL,
  `purchase_price` VARCHAR(75) NULL,
  `list_price` VARCHAR(75) NULL,
  `moving_stat_key` int(11) NOT NULL,
  `commision_apply` varchar(5) DEFAULT '',
  `comm_percent` double(6,2) DEFAULT '0.00',
  `storage_mstr_key` int(11) NOT NULL,
  `self_no` VARCHAR(75) NULL,
  `total_weight` double(18,2) DEFAULT '0.00',
  `weight_unit` VARCHAR(11) DEFAULT NULL,
  `current_stock` INT(11) DEFAULT 0,
  `min_stock` INT(11) DEFAULT 0,
  `max_stock` INT(11) DEFAULT 0,
  `stock_unit` VARCHAR(11) DEFAULT NULL,
  `stock_status` VARCHAR(11) DEFAULT NULL,
  `isnew_product` enum('Y', 'N') DEFAULT 'N',
  `mail_status` varchar(1) DEFAULT 'N',
  `status` enum('A', 'IA') DEFAULT 'A',
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_date` datetime DEFAULT (CURRENT_DATE),
  `updated_by` VARCHAR(100) DEFAULT NULL,
  `updated_date` datetime DEFAULT (CURRENT_DATE),
  PRIMARY KEY (`id`),
  KEY `mfgr_mstr` (`cat1_key`),
  KEY `item_mstr` (`cat2_key`),
  KEY `segment_mstr` (`cat3_key`),
  KEY `vehicle_type_mstr` (`cat4_key`),
  KEY `vehicle_specification_mstr` (`cat5_key`),
  KEY `type_mstr` (`cat6_key`),
  KEY `item_cat7_mstr` (`cat7_key`),
  KEY `item_move_status` (`moving_stat_key`),
  KEY `storage_location_mstr` (`storage_mstr_key`),
);


INSERT INTO `product_mstr` (
  `cat1_key`, 
  `cat2_key`, 
  `cat3_key`, 
  `cat4_key`, 
  `cat5_key`, 
  `cat6_key`, 
  `cat7_key`, 
  `part_no`, 
  `prod_name`, 
  `short_name`, 
  `HSN_code`, 
  `mrp_price`,
  `sales_price`, 
  `purchase_price`, 
  `list_price`, 
  `moving_stat_key`, 
  `commision_apply`, 
  `comm_percent`, 
  `storage_mstr_key`, 
  `self_no`, 
  `total_weight`,
  `weight_unit`,
  `stock_unit`,
  `isnew_product`
  `created_by
)VALUES ()